# Generated by Django 3.2.5 on 2021-11-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('describe', models.TextField(default='Add a new note')),
            ],
        ),
    ]
